def merge(a: dict, b: dict) -> dict:
    a.update(b)
    return a


WEAPON_STYLES = {
    'Magic': {
        'Accurate': {
            'modifiers': {'magic_modifier': 3},
            'magic': {'attack_style': 'MAGIC_ATTACK_STYLE_ACCURATE'},
        },
        'Defensive': {
            'modifiers': {'defence_modifier': 3},
            'magic': {'attack_style': 'MAGIC_ATTACK_STYLE_DEFENSIVE'},
        },
        'Autocast': {
            # The base attack range for staves is 1 to account for melee combat options.
            'modifiers': {'attack_range_modifier': 9},
            'magic': {'attack_style': 'MAGIC_ATTACK_STYLE_AUTOCAST'},
        },
        'Defensive Autocast': {
            # The base attack range for staves is 1 to account for melee combat options.
            'modifiers': {'attack_range_modifier': 9},
            'magic': {'attack_style': 'MAGIC_ATTACK_STYLE_DEFENSIVE_AUTOCAST'},
        },
        'Longrange': {
            'modifiers': {'magic_modifier': 1, 'defence_modifier': 3, 'attack_range_modifier': 2},
            'magic': {'attack_style': 'MAGIC_ATTACK_STYLE_LONGRANGE'},
        },
    },
    'Melee': {
        'Accurate': {
            'modifiers': {'attack_modifier': 3},
            'melee': {'attack_style': 'MELEE_ATTACK_STYLE_ACCURATE'},
        },
        'Aggressive': {
            'modifiers': {'strength_modifier': 3},
            'melee': {'attack_style': 'MELEE_ATTACK_STYLE_AGGRESSIVE'},
        },
        'Controlled': {
            'modifiers': {'attack_modifier': 1, 'strength_modifier': 1, 'defence_modifier': 1},
            'melee': {'attack_style': 'MELEE_ATTACK_STYLE_CONTROLLED'},
        },
        'Defensive': {
            'modifiers': {'defence_modifier': 3},
            'melee': {'attack_style': 'MELEE_ATTACK_STYLE_DEFENSIVE'},
        },
    },
    'Ranged': {
        'Accurate': {
            'modifiers': {'ranged_modifier': 3},
            'ranged': {'attack_style': 'RANGED_ATTACK_STYLE_ACCURATE'},
        },
        'Rapid': {
            'modifiers': {'attack_speed_modifier': -1},
            'ranged': {'attack_style': 'RANGED_ATTACK_STYLE_RAPID'},
        },
        'Longrange': {
            'modifiers': {'defence_modifier': 3},
            'ranged': {'attack_style': 'RANGED_ATTACK_STYLE_LONGRANGE'},
        },
        'Short fuse': {
            'modifiers': {'ranged_modifier': 3},
            'ranged': {'attack_style': 'RANGED_ATTACK_STYLE_ACCURATE'},
        },
        'Medium fuse': {
            'ranged': {'attack_style': 'RANGED_ATTACK_STYLE_RAPID'},
        },
        'Long fuse': {
            'modifiers': {'attack_range_modifier': 1},
            'ranged': {'attack_style': 'RANGED_ATTACK_STYLE_LONGRANGE'},
        },
    },
    'None': {},
}

WEAPON_TYPES = {
    '2h Sword': [
        merge({'name': 'Chop', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Slash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Smash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Axe': [
        merge({'name': 'Chop', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Hack', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Smash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Banner': [
        merge({'name': 'Lunge', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Swipe', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Pound', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Controlled']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Bladed Staff': [
        merge({'name': 'Jab', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}}, WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Swipe', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Fend', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Defensive']),
        merge({'name': 'Spell'}, WEAPON_STYLES['Magic']['Defensive Autocast']),
        merge({'name': 'Spell'}, WEAPON_STYLES['Magic']['Autocast']),
    ],
    'Bludgeon': [
        merge({'name': 'Pound', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Pummel', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Smash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
    ],
    'Blunt': [
        merge({'name': 'Pound', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Pummel', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Bow': [
        merge({'name': 'Accurate'}, WEAPON_STYLES['Ranged']['Accurate']),
        merge({'name': 'Rapid'}, WEAPON_STYLES['Ranged']['Rapid']),
        merge({'name': 'Longrange'}, WEAPON_STYLES['Ranged']['Longrange']),
    ],
    'Bulwark': [
        merge({'name': 'Pummel', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Block'}, WEAPON_STYLES['None']),
    ],
    'Chinchompas': [
        merge({'name': 'Short fuse'}, WEAPON_STYLES['Ranged']['Short fuse']),
        merge({'name': 'Medium fuse'}, WEAPON_STYLES['Ranged']['Medium fuse']),
        merge({'name': 'Long fuse'}, WEAPON_STYLES['Ranged']['Long fuse']),
    ],
    'Claw': [
        merge({'name': 'Chop', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Slash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Lunge', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Controlled']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Crossbow': [
        merge({'name': 'Accurate'}, WEAPON_STYLES['Ranged']['Accurate']),
        merge({'name': 'Rapid'}, WEAPON_STYLES['Ranged']['Rapid']),
        merge({'name': 'Longrange'}, WEAPON_STYLES['Ranged']['Longrange']),
    ],
    'Gun': [
        merge({'name': 'Aim and Fire'}, WEAPON_STYLES['None']),
        merge({'name': 'Kick', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
    ],
    'Partisan': [
        merge({'name': 'Stab', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}}, WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Lunge', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Pound', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Pickaxe': [
        merge({'name': 'Spike', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Impale', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Smash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Polearm': [
        merge({'name': 'Jab', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Controlled']),
        merge({'name': 'Swipe', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Fend', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Polestaff': [
        merge({'name': 'Bash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Pound', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Powered Staff': [
        merge({'name': 'Accurate'}, WEAPON_STYLES['Magic']['Accurate']),
        merge({'name': 'Accurate'}, WEAPON_STYLES['Magic']['Accurate']),
        merge({'name': 'Longrange'}, WEAPON_STYLES['Magic']['Longrange']),
    ],
    'Powered Wand': [
        merge({'name': 'Accurate'}, WEAPON_STYLES['Magic']['Accurate']),
        merge({'name': 'Accurate'}, WEAPON_STYLES['Magic']['Accurate']),
        merge({'name': 'Longrange'}, WEAPON_STYLES['Magic']['Longrange']),
    ],
    'Salamander': [
        merge({'name': 'Scorch', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Flare'}, WEAPON_STYLES['Ranged']['Accurate']),
        merge({'name': 'Blaze'}, WEAPON_STYLES['Magic']['Defensive']),
    ],
    'Scythe': [
        merge({'name': 'Reap', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Chop', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Jab', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Slash Sword': [
        merge({'name': 'Chop', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Slash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Lunge', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Controlled']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Spear': [
        merge({'name': 'Lunge', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Controlled']),
        merge({'name': 'Swipe', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Controlled']),
        merge({'name': 'Pound', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Controlled']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Spiked': [
        merge({'name': 'Pound', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Pummel', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Spike', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Controlled']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Stab Sword': [
        merge({'name': 'Stab', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Lunge', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Slash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_STAB'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Staff': [
        merge({'name': 'Bash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Pound', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Focus', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Defensive']),
        merge({'name': 'Spell'}, WEAPON_STYLES['Magic']['Defensive Autocast']),
        merge({'name': 'Spell'}, WEAPON_STYLES['Magic']['Autocast']),
    ],
    'Thrown': [
        merge({'name': 'Accurate'}, WEAPON_STYLES['Ranged']['Accurate']),
        merge({'name': 'Rapid'}, WEAPON_STYLES['Ranged']['Rapid']),
        merge({'name': 'Longrange'}, WEAPON_STYLES['Ranged']['Longrange']),
    ],
    'Unarmed': [
        merge({'name': 'Punch', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Kick', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Aggressive']),
        merge({'name': 'Block', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_CRUSH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
    'Whip': [
        merge({'name': 'Flick', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Accurate']),
        merge({'name': 'Lash', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Controlled']),
        merge({'name': 'Deflect', 'melee': {'attack_type': 'MELEE_ATTACK_TYPE_SLASH'}},
              WEAPON_STYLES['Melee']['Defensive']),
    ],
}
